In [1]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 46.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 30.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 84.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 76.0 MB/s eta 0:00:00


In [7]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification,RobertaModel, RobertaForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("SamLowe/roberta-base-go_emotions")
model = RobertaModel.from_pretrained("SamLowe/roberta-base-go_emotions", add_pooling_layer = False)

In [8]:
inp = tokenizer("I have bad day", return_tensors="pt")
out1 = model(**inp)[0][:, 0, :]

In [9]:
inp = tokenizer("I have a great day", return_tensors="pt")
out2 = model(**inp)[0][:, 0, :]

In [10]:
from torch.nn import functional as F

In [11]:
F.cosine_similarity(out1, out2)

tensor([0.2243], grad_fn=<SumBackward1>)

In [2]:
from transformers import AutoTokenizer, RobertaModel


tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-emotion-multilabel-latest")
model = RobertaModel.from_pretrained("cardiffnlp/twitter-roberta-base-emotion-multilabel-latest", add_pooling_layer = False)

[2023-11-07 00:17:31,389] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)


In [5]:
inp = tokenizer("I have bad day", return_tensors="pt")
out1 = model(**inp)[0][:, 0, :]

In [6]:
inp = tokenizer("I have a great day", return_tensors="pt")
out2 = model(**inp)[0][:, 0, :]

In [7]:
from torch.nn import functional as F


F.cosine_similarity(out1, out2)

tensor([-0.1409], grad_fn=<SumBackward1>)

In [ ]:
F.pdist()

In [11]:
(1 -0.14) / 2

0.43

In [12]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")
model = RobertaModel.from_pretrained("roberta-base", add_pooling_layer = False)

In [13]:
inp = tokenizer("I have bad day", return_tensors="pt")
out1 = model(**inp)[0][:, 0, :]

In [14]:
inp = tokenizer("I have a great day", return_tensors="pt")
out2 = model(**inp)[0][:, 0, :]

In [15]:
from torch.nn import functional as F

In [16]:
F.cosine_similarity(out1, out2)

tensor([0.9996], grad_fn=<SumBackward1>)